### ISSUE TITLE
Usage instructions missing

### ISSUE THREAD

**Issue by kaj** [KTH/kth-style#1]
Instructions for how to use kth-style in a node project has gone missing.   https://app.kth.se/style/ contais a link to https://github.com/KTH/kth-style#how-to-start-using-kth-style , but that section does not exists in the `README.md`.

A short but complete such usage section would be appropriate.

**Comment by hoyce** [comment]
This is now solved by the current information on https://app.kth.se/style/setup-guide/setup. Also, if one use the node-web template it is already integrated.
