### ISSUE TITLE
Sorteringsikoner har ev fel färg i senaste kth-style

### ISSUE THREAD

**Issue by jhsware** [KTH/kth-style#9]
I produktion är sorteringsikoner ljusgråa, men i senaste kth-style är de svarta.

**Comment by wonkyung** [comment]
Vet inte exakt vilken ikon du menar men denna **arrow-sort-default-white.svg** använder vi t.ex. i tabell huvud. Den är vit mot grå bakgrund när den är 'vald'. När den inte är vald så har den opacity:1 vilket gör den till grå. Och så långt jag kan se så är det fortfarande vit men blir grå när den inte är vald, både i produktion och i v7.0.2 av kth-style. FÖ använder de flesta av 'våra' node appar den senaste versionen.

Men det kanske finns någon annan ikon som har blivit knasig eller i något läge det beter sig konstigt.

**Comment by hoyce** [comment]
@jhsware Den där ikonen ser ut att komma från lms-web som är inproxad i Cortina. D.v.s. den ser ut att ligga i lms-web (https://github.com/KTH/lms-web/blob/master/public/style.css) och alltså inte i kth-style.
